fn main() {
    // tauri-build writes a permission file per listed command but never removes
    // one for a command that was dropped; start clean so the ACL matches the list.
    match std::fs::remove_dir_all("permissions/autogenerated") {
        Ok(()) => {}
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => {}
        Err(err) => panic!("clearing permissions/autogenerated: {err}"),
    }
    tauri_build::try_build(
        tauri_build::Attributes::new().app_manifest(tauri_build::AppManifest::new().commands(APP_COMMANDS)),
    )
    .expect("failed to run tauri-build");
}

/// Every command in `lib.rs`'s `generate_handler!`. With an app manifest, Tauri
/// checks app commands against capabilities: `capabilities/default.json`
/// grants all of them to the main webview, and `capabilities/makerworld-remote.json`
/// grants the remote MakerWorld webview only its two report commands.
/// `acl_tests` in `lib.rs` keeps the three lists in sync.
const APP_COMMANDS: &[&str] = &[
    "get_app_state",
    "set_active_view",
    "sync_makerworld_webview",
    "navigate_makerworld",
    "search_makerworld",
    "makerworld_back",
    "makerworld_forward",
    "makerworld_reload",
    "download_model",
    "report_makerworld_page",
    "report_makerworld_import_attempt",
    "connect_printer",
    "disconnect_printer",
    "get_printer_status",
    "probe_camera",
    "pause_print",
    "resume_print",
    "start_print",
    "list_profiles",
    "slice_model",
    "read_model_file",
    "read_text_file",
    "write_text_file",
    "add_to_queue",
    "get_queue",
    "remove_from_queue",
    "get_print_history",
    "mcp_status",
    "mcp_set_enabled",
    "mcp_token",
    "mcp_rotate_token",
    "sign_build",
    "sign_cancel",
    "sign_list",
    "sign_lineage",
    "sign_get",
    "sign_preview",
    "sign_approve",
    "sign_export",
    "sign_record_print",
    "agent_status",
    "agent_set_api_key",
    "agent_clear_api_key",
    "agent_set_model",
    "agent_history",
    "agent_new_conversation",
    "agent_send",
    "agent_cancel",
    "delete_print_history_item",
    "get_library_models",
    "search_library_models",
    "delete_library_model",
    "open_library_model",
    "openscad_check_installed",
    "openscad_extract_params",
    "openscad_render",
    "get_designs_dir",
    "store_credential",
    "get_credential",
    "delete_credential",
    "has_credential",
    "add_printer_config",
    "update_printer_config",
    "delete_printer_config",
    "get_printer_configs",
    "set_default_printer",
    "connect_printer_by_config",
    "switch_printer",
    "get_settings",
    "update_settings",
    "bambu_studio_status",
    "choose_bambu_studio",
    "clear_bambu_studio",
];
